/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.livraria.telas;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author yago.aguiar
 */
public class TelaCadastros extends javax.swing.JFrame {

    private static final String usuario = "root";
    private static final String senha = "1234";
    private static final String dataConn = "jdbc:mysql://localhost:3306/livrariadb";
    
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q, i, id, deleteItem;
    
    
    
    public TelaCadastros() {
        initComponents();
        updateDB();
 
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.WARNING: Do NOT modify this code.
     * The content of this method is always
 regenerated by the Form Editor.
     * @return 
     */
    
    public boolean validarCamposEditora() {
        if(txtNomeEditora.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Nome é obrigatório.");
            if(txtNomeEditora.getText().length() > 255) {
                JOptionPane.showMessageDialog(null, "Caracteres não pode ser maior que 255"); 
            }
            return false;
        }
        return true;
        
    }
    
    // Atualiza a tabela com dados do banco
    public void updateDB() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn,usuario,senha);
            pst = sqlConn.prepareStatement("select * from editora");
            
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)editoraTable.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next()) {
                Vector columnData = new Vector();
                for (i = 1; i <= q; i++) {
                    columnData.add(rs.getInt("id_editora"));
                    columnData.add(rs.getString("nome_editora"));
                    columnData.add(rs.getString("telefone"));
                    columnData.add(rs.getString("email"));
                }
                RecordTable.addRow(columnData);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        editoraPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        editoraTable = new javax.swing.JTable();
        editarEditoraButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtIdEditora = new javax.swing.JTextField();
        txtNomeEditora = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        adicionarNovaEditoraButton = new javax.swing.JButton();
        txtTelefoneEditora = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        excluirEditoraButton = new javax.swing.JButton();
        txtEmailEditora = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtPesquisaEditora = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        livroPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        adicionarNovoButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtIdLivro = new javax.swing.JTextField();
        txtTituloLivro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        adicionarNovoLivroButton = new javax.swing.JButton();
        txtAutorLivro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        adicionarNovoButton2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        txtPrecoLivro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtQuantidadeLivro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle Livraria");
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 578));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        editoraTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Telefone", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        editoraTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        editoraTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editoraTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(editoraTable);

        editarEditoraButton.setBackground(new java.awt.Color(255, 51, 51));
        editarEditoraButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        editarEditoraButton.setForeground(new java.awt.Color(255, 255, 255));
        editarEditoraButton.setText("Editar");
        editarEditoraButton.setBorder(null);
        editarEditoraButton.setBorderPainted(false);
        editarEditoraButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editarEditoraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarEditoraButtonActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Editora ID");
        jLabel12.setToolTipText("");

        txtIdEditora.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtIdEditora.setForeground(new java.awt.Color(51, 51, 51));
        txtIdEditora.setToolTipText("");
        txtIdEditora.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        txtIdEditora.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtIdEditora.setEnabled(false);
        txtIdEditora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdEditoraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdEditoraFocusLost(evt);
            }
        });
        txtIdEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEditoraActionPerformed(evt);
            }
        });

        txtNomeEditora.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtNomeEditora.setForeground(new java.awt.Color(51, 51, 51));
        txtNomeEditora.setToolTipText("");
        txtNomeEditora.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        txtNomeEditora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeEditoraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeEditoraFocusLost(evt);
            }
        });
        txtNomeEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeEditoraActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Nome");
        jLabel13.setToolTipText("");

        adicionarNovaEditoraButton.setBackground(new java.awt.Color(255, 51, 51));
        adicionarNovaEditoraButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        adicionarNovaEditoraButton.setForeground(new java.awt.Color(255, 255, 255));
        adicionarNovaEditoraButton.setBorder(null);
        adicionarNovaEditoraButton.setBorderPainted(false);
        adicionarNovaEditoraButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adicionarNovaEditoraButton.setLabel("Adicionar Novo");
        adicionarNovaEditoraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarNovaEditoraButtonActionPerformed(evt);
            }
        });

        txtTelefoneEditora.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtTelefoneEditora.setForeground(new java.awt.Color(51, 51, 51));
        txtTelefoneEditora.setToolTipText("");
        txtTelefoneEditora.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        txtTelefoneEditora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefoneEditoraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefoneEditoraFocusLost(evt);
            }
        });
        txtTelefoneEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneEditoraActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Telefone");
        jLabel14.setToolTipText("");

        excluirEditoraButton.setBackground(new java.awt.Color(255, 51, 51));
        excluirEditoraButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        excluirEditoraButton.setForeground(new java.awt.Color(255, 255, 255));
        excluirEditoraButton.setText("Excluir");
        excluirEditoraButton.setBorder(null);
        excluirEditoraButton.setBorderPainted(false);
        excluirEditoraButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        excluirEditoraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirEditoraButtonActionPerformed(evt);
            }
        });

        txtEmailEditora.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtEmailEditora.setForeground(new java.awt.Color(51, 51, 51));
        txtEmailEditora.setToolTipText("");
        txtEmailEditora.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        txtEmailEditora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailEditoraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailEditoraFocusLost(evt);
            }
        });
        txtEmailEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailEditoraActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(51, 51, 51));
        jLabel16.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Email");
        jLabel16.setToolTipText("");

        txtPesquisaEditora.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtPesquisaEditora.setForeground(new java.awt.Color(51, 51, 51));
        txtPesquisaEditora.setToolTipText("");
        txtPesquisaEditora.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        txtPesquisaEditora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesquisaEditoraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPesquisaEditoraFocusLost(evt);
            }
        });
        txtPesquisaEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaEditoraActionPerformed(evt);
            }
        });
        txtPesquisaEditora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesquisaEditoraKeyTyped(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(51, 51, 51));
        jLabel17.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Pesquisar por nome");
        jLabel17.setToolTipText("");

        javax.swing.GroupLayout editoraPanelLayout = new javax.swing.GroupLayout(editoraPanel);
        editoraPanel.setLayout(editoraPanelLayout);
        editoraPanelLayout.setHorizontalGroup(
            editoraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editoraPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editoraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editoraPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(editoraPanelLayout.createSequentialGroup()
                        .addGroup(editoraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editoraPanelLayout.createSequentialGroup()
                                .addComponent(txtIdEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(adicionarNovaEditoraButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                            .addGroup(editoraPanelLayout.createSequentialGroup()
                                .addComponent(txtNomeEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addGroup(editoraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editarEditoraButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(excluirEditoraButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(editoraPanelLayout.createSequentialGroup()
                                .addGroup(editoraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 490, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(editoraPanelLayout.createSequentialGroup()
                        .addGroup(editoraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefoneEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(editoraPanelLayout.createSequentialGroup()
                        .addGroup(editoraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmailEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPesquisaEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        editoraPanelLayout.setVerticalGroup(
            editoraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editoraPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editoraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarNovaEditoraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editoraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editoraPanelLayout.createSequentialGroup()
                        .addComponent(editarEditoraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirEditoraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editoraPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefoneEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmailEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisaEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Editoras", editoraPanel);

        livroPanel.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Título", "Autor", "Data Publicação", "Preço", "Quantidade", "Editora"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        adicionarNovoButton.setBackground(new java.awt.Color(255, 51, 51));
        adicionarNovoButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        adicionarNovoButton.setForeground(new java.awt.Color(255, 255, 255));
        adicionarNovoButton.setText("Editar");
        adicionarNovoButton.setBorder(null);
        adicionarNovoButton.setBorderPainted(false);
        adicionarNovoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adicionarNovoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarNovoButtonActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Livro ID");
        jLabel2.setToolTipText("");

        txtIdLivro.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtIdLivro.setForeground(new java.awt.Color(51, 51, 51));
        txtIdLivro.setToolTipText("");
        txtIdLivro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        txtIdLivro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtIdLivro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdLivroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdLivroFocusLost(evt);
            }
        });
        txtIdLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdLivroActionPerformed(evt);
            }
        });

        txtTituloLivro.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtTituloLivro.setForeground(new java.awt.Color(51, 51, 51));
        txtTituloLivro.setToolTipText("");
        txtTituloLivro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        txtTituloLivro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTituloLivroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTituloLivroFocusLost(evt);
            }
        });
        txtTituloLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloLivroActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Título");
        jLabel3.setToolTipText("");

        adicionarNovoLivroButton.setBackground(new java.awt.Color(255, 51, 51));
        adicionarNovoLivroButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        adicionarNovoLivroButton.setForeground(new java.awt.Color(255, 255, 255));
        adicionarNovoLivroButton.setBorder(null);
        adicionarNovoLivroButton.setBorderPainted(false);
        adicionarNovoLivroButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adicionarNovoLivroButton.setLabel("Adicionar Novo");
        adicionarNovoLivroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarNovoLivroButtonActionPerformed(evt);
            }
        });

        txtAutorLivro.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtAutorLivro.setForeground(new java.awt.Color(51, 51, 51));
        txtAutorLivro.setToolTipText("");
        txtAutorLivro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        txtAutorLivro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAutorLivroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAutorLivroFocusLost(evt);
            }
        });
        txtAutorLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorLivroActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Autor");
        jLabel4.setToolTipText("");

        adicionarNovoButton2.setBackground(new java.awt.Color(255, 51, 51));
        adicionarNovoButton2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        adicionarNovoButton2.setForeground(new java.awt.Color(255, 255, 255));
        adicionarNovoButton2.setText("Excluir");
        adicionarNovoButton2.setBorder(null);
        adicionarNovoButton2.setBorderPainted(false);
        adicionarNovoButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adicionarNovoButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarNovoButton2ActionPerformed(evt);
            }
        });

        jDateChooser1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Data Publicação");
        jLabel7.setToolTipText("");

        txtPrecoLivro.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtPrecoLivro.setForeground(new java.awt.Color(51, 51, 51));
        txtPrecoLivro.setToolTipText("");
        txtPrecoLivro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        txtPrecoLivro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPrecoLivroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecoLivroFocusLost(evt);
            }
        });
        txtPrecoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoLivroActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Preço");
        jLabel9.setToolTipText("");

        txtQuantidadeLivro.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtQuantidadeLivro.setForeground(new java.awt.Color(51, 51, 51));
        txtQuantidadeLivro.setToolTipText("");
        txtQuantidadeLivro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        txtQuantidadeLivro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQuantidadeLivroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQuantidadeLivroFocusLost(evt);
            }
        });
        txtQuantidadeLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeLivroActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Quantidade");
        jLabel10.setToolTipText("");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Editora");
        jLabel11.setToolTipText("");

        javax.swing.GroupLayout livroPanelLayout = new javax.swing.GroupLayout(livroPanel);
        livroPanel.setLayout(livroPanelLayout);
        livroPanelLayout.setHorizontalGroup(
            livroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(livroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(livroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(livroPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(livroPanelLayout.createSequentialGroup()
                        .addGroup(livroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(livroPanelLayout.createSequentialGroup()
                                .addComponent(txtIdLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(adicionarNovoLivroButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                            .addGroup(livroPanelLayout.createSequentialGroup()
                                .addComponent(txtTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addGroup(livroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adicionarNovoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(adicionarNovoButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(livroPanelLayout.createSequentialGroup()
                                .addGroup(livroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(livroPanelLayout.createSequentialGroup()
                        .addGroup(livroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(livroPanelLayout.createSequentialGroup()
                                .addGroup(livroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(livroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecoLivro)))
                            .addComponent(txtAutorLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(livroPanelLayout.createSequentialGroup()
                                .addGroup(livroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txtQuantidadeLivro, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(livroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        livroPanelLayout.setVerticalGroup(
            livroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(livroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(livroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(livroPanelLayout.createSequentialGroup()
                        .addGroup(livroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adicionarNovoLivroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(livroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(livroPanelLayout.createSequentialGroup()
                                .addComponent(adicionarNovoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adicionarNovoButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(livroPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAutorLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(livroPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(livroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(livroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1)
                    .addComponent(txtQuantidadeLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Livros", livroPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 575));

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setMinimumSize(new java.awt.Dimension(300, 0));
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("French Script MT", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("BiblioTech");

        jLabel6.setBackground(new java.awt.Color(255, 0, 0));
        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons8_Library_50px_1.png"))); // NOI18N
        jLabel6.setText("Página Inicial");
        jLabel6.setToolTipText("");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 0, 0));
        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons8_User_50px.png"))); // NOI18N
        jLabel8.setText("Cadastros");
        jLabel8.setToolTipText("");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(380, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(822, 586));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarNovoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarNovoButtonActionPerformed
        
    }//GEN-LAST:event_adicionarNovoButtonActionPerformed

    private void txtIdLivroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdLivroFocusGained
        
    }//GEN-LAST:event_txtIdLivroFocusGained

    private void txtIdLivroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdLivroFocusLost
        
    }//GEN-LAST:event_txtIdLivroFocusLost

    private void txtIdLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdLivroActionPerformed

    private void txtTituloLivroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTituloLivroFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloLivroFocusGained

    private void txtTituloLivroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTituloLivroFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloLivroFocusLost

    private void txtTituloLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloLivroActionPerformed

    private void adicionarNovoLivroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarNovoLivroButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adicionarNovoLivroButtonActionPerformed

    private void txtAutorLivroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAutorLivroFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorLivroFocusGained

    private void txtAutorLivroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAutorLivroFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorLivroFocusLost

    private void txtAutorLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorLivroActionPerformed

    private void adicionarNovoButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarNovoButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adicionarNovoButton2ActionPerformed

    private void txtPrecoLivroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecoLivroFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoLivroFocusGained

    private void txtPrecoLivroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecoLivroFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoLivroFocusLost

    private void txtPrecoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoLivroActionPerformed

    private void txtQuantidadeLivroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantidadeLivroFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeLivroFocusGained

    private void txtQuantidadeLivroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantidadeLivroFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeLivroFocusLost

    private void txtQuantidadeLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeLivroActionPerformed

    private void editarEditoraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarEditoraButtonActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn,usuario,senha);
            pst = sqlConn.prepareStatement("update livrariadb.editora set nome_editora = ?, telefone = ?, email = ? "
                    + "where id_editora = ?");
                    
            pst.setString(1, txtNomeEditora.getText());
            pst.setString(2, txtTelefoneEditora.getText());
            pst.setString(3, txtEmailEditora.getText());
            pst.setString(4, txtIdEditora.getText());
            
            pst.executeUpdate();
            // fazer metodo validação
            if(!txtIdEditora.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Editora atualizada com sucesso!");
            }
            else {
                JOptionPane.showMessageDialog(this, "Selecione uma editora.");
            }
            
            updateDB();
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }        
    }//GEN-LAST:event_editarEditoraButtonActionPerformed

    private void txtIdEditoraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdEditoraFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEditoraFocusGained

    private void txtIdEditoraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdEditoraFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEditoraFocusLost

    private void txtIdEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEditoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEditoraActionPerformed

    private void txtNomeEditoraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeEditoraFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeEditoraFocusGained

    private void txtNomeEditoraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeEditoraFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeEditoraFocusLost

    private void txtNomeEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeEditoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeEditoraActionPerformed

    private void adicionarNovaEditoraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarNovaEditoraButtonActionPerformed
        if(validarCamposEditora()) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn,usuario,senha);
            pst = sqlConn.prepareStatement("insert into livrariadb.editora(nome_editora,telefone,email)"
                    + "values(?,?,?)");
            pst.setString(1, txtNomeEditora.getText());
            pst.setString(2, txtTelefoneEditora.getText());
            pst.setString(3, txtEmailEditora.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Editora adicionada com sucesso!");
            updateDB();
            txtIdEditora.setText("");
            txtNomeEditora.setText("");
            txtTelefoneEditora.setText("");
            txtEmailEditora.setText("");
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        }
    }//GEN-LAST:event_adicionarNovaEditoraButtonActionPerformed

    private void txtTelefoneEditoraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefoneEditoraFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneEditoraFocusGained

    private void txtTelefoneEditoraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefoneEditoraFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneEditoraFocusLost

    private void txtTelefoneEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneEditoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneEditoraActionPerformed

    private void excluirEditoraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirEditoraButtonActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel)editoraTable.getModel();
        int SelectedRows = editoraTable.getSelectedRow();
        try {
            id = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
            deleteItem = JOptionPane.showConfirmDialog(null,"Tem certeza que deseja excluir essa editora?",
                    "Warning",JOptionPane.YES_NO_OPTION);
            if (deleteItem == JOptionPane.YES_OPTION) {
                Class.forName("com.mysql.jdbc.Driver");
                sqlConn = DriverManager.getConnection(dataConn,usuario,senha);
                pst = sqlConn.prepareStatement("delete from livrariadb.editora where id_editora = ?");
                pst.setInt(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Editora excluida com sucesso!");
                updateDB();
                
                txtIdEditora.setText("");
                txtNomeEditora.setText("");
                txtTelefoneEditora.setText("");
                txtEmailEditora.setText("");
  
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastros.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
            
        } catch (SQLException ex) {
            System.err.println(ex);
        }
    }//GEN-LAST:event_excluirEditoraButtonActionPerformed

    private void txtEmailEditoraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailEditoraFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailEditoraFocusGained

    private void txtEmailEditoraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailEditoraFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailEditoraFocusLost

    private void txtEmailEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailEditoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailEditoraActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        TelaPrincipal telaPrincipal = new TelaPrincipal();
        telaPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        jLabel6.setOpaque(true);
        jLabel6.setBackground(new java.awt.Color(255, 77, 77));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited

        jLabel6.setBackground(new java.awt.Color(255,0,0));
        jLabel6.setOpaque(false);
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        TelaCadastros telaCadastroLivro = new TelaCadastros();
        telaCadastroLivro.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        jLabel8.setOpaque(true);
        jLabel8.setBackground(new java.awt.Color(255, 77, 77));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        jLabel8.setBackground(new java.awt.Color(255,0,0));
        jLabel8.setOpaque(false);
    }//GEN-LAST:event_jLabel8MouseExited

    private void editoraTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editoraTableMouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)editoraTable.getModel();
        int SelectedRows = editoraTable.getSelectedRow();
        
        txtIdEditora.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
        txtNomeEditora.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        txtTelefoneEditora.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
        txtEmailEditora.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
    }//GEN-LAST:event_editoraTableMouseClicked

    private void txtPesquisaEditoraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaEditoraFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaEditoraFocusGained

    private void txtPesquisaEditoraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaEditoraFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaEditoraFocusLost

    private void txtPesquisaEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaEditoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaEditoraActionPerformed

    private void txtPesquisaEditoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaEditoraKeyTyped
        try {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn,usuario,senha);
            pst = sqlConn.prepareStatement("select * from editora where nome_editora like ? ");
            pst.setString(1, "%" + txtPesquisaEditora.getText() + "%");
            System.out.println(txtPesquisaEditora.getText());
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)editoraTable.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next()) {
                Vector columnData = new Vector();
                for (i = 1; i <= q; i++) {
                    columnData.add(rs.getInt("id_editora"));
                    columnData.add(rs.getString("nome_editora"));
                    columnData.add(rs.getString("telefone"));
                    columnData.add(rs.getString("email"));
                }
                RecordTable.addRow(columnData);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_txtPesquisaEditoraKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarNovaEditoraButton;
    private javax.swing.JButton adicionarNovoButton;
    private javax.swing.JButton adicionarNovoButton2;
    private javax.swing.JButton adicionarNovoLivroButton;
    private javax.swing.JButton editarEditoraButton;
    private javax.swing.JPanel editoraPanel;
    private javax.swing.JTable editoraTable;
    private javax.swing.JButton excluirEditoraButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel livroPanel;
    private javax.swing.JTextField txtAutorLivro;
    private javax.swing.JTextField txtEmailEditora;
    private javax.swing.JTextField txtIdEditora;
    private javax.swing.JTextField txtIdLivro;
    private javax.swing.JTextField txtNomeEditora;
    private javax.swing.JTextField txtPesquisaEditora;
    private javax.swing.JTextField txtPrecoLivro;
    private javax.swing.JTextField txtQuantidadeLivro;
    private javax.swing.JTextField txtTelefoneEditora;
    private javax.swing.JTextField txtTituloLivro;
    // End of variables declaration//GEN-END:variables
}
